from pydantic import Field
from .models import Assignment

Times = {
    0  : Assignment(startDate="", endDate="", beginTime="0830", endTime="0950", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    1  : Assignment(startDate="", endDate="", beginTime="0900", endTime="1020", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    2  : Assignment(startDate="", endDate="", beginTime="0930", endTime="1050", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    3  : Assignment(startDate="", endDate="", beginTime="1000", endTime="1120", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    4  : Assignment(startDate="", endDate="", beginTime="1030", endTime="1150", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    5  : Assignment(startDate="", endDate="", beginTime="1100", endTime="1220", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    6  : Assignment(startDate="", endDate="", beginTime="1130", endTime="1250", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    7  : Assignment(startDate="", endDate="", beginTime="1200", endTime="1320", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    8  : Assignment(startDate="", endDate="", beginTime="1230", endTime="1350", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    9  : Assignment(startDate="", endDate="", beginTime="1300", endTime="1420", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    10 : Assignment(startDate="", endDate="", beginTime="1330", endTime="1450", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    11 : Assignment(startDate="", endDate="", beginTime="1400", endTime="1520", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    12 : Assignment(startDate="", endDate="", beginTime="1430", endTime="1550", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    13 : Assignment(startDate="", endDate="", beginTime="1500", endTime="1620", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    14 : Assignment(startDate="", endDate="", beginTime="1530", endTime="1650", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    15 : Assignment(startDate="", endDate="", beginTime="1600", endTime="1720", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    16 : Assignment(startDate="", endDate="", beginTime="1630", endTime="1750", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    17 : Assignment(startDate="", endDate="", beginTime="1700", endTime="1820", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    18 : Assignment(startDate="", endDate="", beginTime="1730", endTime="1850", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    19 : Assignment(startDate="", endDate="", beginTime="1800", endTime="1920", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    20 : Assignment(startDate="", endDate="", beginTime="1830", endTime="1950", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    21 : Assignment(startDate="", endDate="", beginTime="1900", endTime="2020", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    22 : Assignment(startDate="", endDate="", beginTime="1930", endTime="2050", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    23 : Assignment(startDate="", endDate="", beginTime="2000", endTime="2120", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    24 : Assignment(startDate="", endDate="", beginTime="2030", endTime="2150", hoursWeek=3, sunday=False, monday=True, tuesday=False, wednesday=False, thursday=True, friday=False, saturday=False),
    25 : Assignment(startDate="", endDate="", beginTime="0830", endTime="0920", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    26 : Assignment(startDate="", endDate="", beginTime="0900", endTime="0950", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    27 : Assignment(startDate="", endDate="", beginTime="0930", endTime="1020", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    28 : Assignment(startDate="", endDate="", beginTime="1000", endTime="1050", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    29 : Assignment(startDate="", endDate="", beginTime="1030", endTime="1120", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    30 : Assignment(startDate="", endDate="", beginTime="1100", endTime="1150", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    31 : Assignment(startDate="", endDate="", beginTime="1130", endTime="1220", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    32 : Assignment(startDate="", endDate="", beginTime="1200", endTime="1250", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    33 : Assignment(startDate="", endDate="", beginTime="1230", endTime="1320", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    34 : Assignment(startDate="", endDate="", beginTime="1300", endTime="1350", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    35 : Assignment(startDate="", endDate="", beginTime="1330", endTime="1420", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    36 : Assignment(startDate="", endDate="", beginTime="1400", endTime="1450", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    37 : Assignment(startDate="", endDate="", beginTime="1430", endTime="1520", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    38 : Assignment(startDate="", endDate="", beginTime="1500", endTime="1550", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    39 : Assignment(startDate="", endDate="", beginTime="1530", endTime="1620", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    40 : Assignment(startDate="", endDate="", beginTime="1600", endTime="1650", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    41 : Assignment(startDate="", endDate="", beginTime="1630", endTime="1720", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    42 : Assignment(startDate="", endDate="", beginTime="1700", endTime="1750", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    43 : Assignment(startDate="", endDate="", beginTime="1730", endTime="1820", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    44 : Assignment(startDate="", endDate="", beginTime="1800", endTime="1850", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    45 : Assignment(startDate="", endDate="", beginTime="1830", endTime="1920", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    46 : Assignment(startDate="", endDate="", beginTime="1900", endTime="1950", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    47 : Assignment(startDate="", endDate="", beginTime="1930", endTime="2020", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    48 : Assignment(startDate="", endDate="", beginTime="2000", endTime="2050", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    49 : Assignment(startDate="", endDate="", beginTime="2030", endTime="2120", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False),
    50 : Assignment(startDate="", endDate="", beginTime="2100", endTime="2150", hoursWeek=3, sunday=False, monday=False, tuesday=True, wednesday=True, thursday=False, friday=True, saturday=False)
}